### ISSUE TITLE
Setup daily job to install all fleet packages

### ISSUE THREAD

**Issue by spalger** [elastic/kibana-buildkite#25]
The fleet team is asking for a pipeline that can run `node scripts/x-pack/plugins/fleet/scripts/install_all_packages` and report any failures to the fleet team.

Kibana issue: https://github.com/elastic/kibana/issues/128493

**Comment by spalger** [comment]
@nchaulet, what slack channel would you like to have notifications sent to?

**Comment by nchaulet** [comment]
> @nchaulet, what slack channel would you like to have notifications sent to?

I think it will be good to have it in fleet (cc @elastic/fleet). The script is not ready to be deployed in CI yet, it return 0 on error, the output is probably not adapted to reporting and the Kibana connection is not configurable.

**Comment by spalger** [comment]
Yeah, for now the job is setup but slack notifications are disabled. We can continue discussion in https://github.com/elastic/kibana/issues/128493. 

Once you're ready to enable slack notifications just update these lines in a PR to this repo: https://github.com/elastic/kibana-buildkite/blob/main/pipelines/kibana-fleet-packages-daily.tf#L7-L9
